# Form implementation generated from reading ui file 'c:\Users\mauri\Repos\GitHub\iligui\dialog_settings.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(295, 192)
        Dialog.setStyleSheet("QRadioButton::indicator:checked, QCheckBox::indicator:checked {\n"
"    image: url(icons/check-circle-green.svg);\n"
"}\n"
"QRadioButton::indicator:unchecked, QCheckBox::indicator:unchecked {\n"
"    image: url(icons/circle.svg);\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setContentsMargins(20, 10, 20, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Title = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.Title.setFont(font)
        self.Title.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.Title.setObjectName("Title")
        self.horizontalLayout.addWidget(self.Title)
        self.configButton = QtWidgets.QToolButton(parent=self.frame)
        self.configButton.setMinimumSize(QtCore.QSize(30, 30))
        self.configButton.setStyleSheet("QToolButton[objectName^=\"configButton\"]:hover {\n"
"    background-color : rgb(230,230,230);\n"
"    border-radius: 15px;\n"
"    border-style: outset;\n"
"}\n"
"\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\mauri\\Repos\\GitHub\\iligui\\icons/tool.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.configButton.setIcon(icon)
        self.configButton.setIconSize(QtCore.QSize(30, 30))
        self.configButton.setAutoRaise(True)
        self.configButton.setObjectName("configButton")
        self.horizontalLayout.addWidget(self.configButton)
        self.verticalLayout_2.addWidget(self.frame, 0, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.selectionFrame = QtWidgets.QFrame(parent=Dialog)
        self.selectionFrame.setEnabled(True)
        self.selectionFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.selectionFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.selectionFrame.setObjectName("selectionFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.selectionFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.transferfileRadiobutton = QtWidgets.QCheckBox(parent=self.selectionFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transferfileRadiobutton.sizePolicy().hasHeightForWidth())
        self.transferfileRadiobutton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.transferfileRadiobutton.setFont(font)
        self.transferfileRadiobutton.setStyleSheet("")
        self.transferfileRadiobutton.setCheckable(True)
        self.transferfileRadiobutton.setChecked(True)
        self.transferfileRadiobutton.setObjectName("transferfileRadiobutton")
        self.verticalLayout.addWidget(self.transferfileRadiobutton)
        self.localsearchRadiobutton = QtWidgets.QCheckBox(parent=self.selectionFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localsearchRadiobutton.sizePolicy().hasHeightForWidth())
        self.localsearchRadiobutton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.localsearchRadiobutton.setFont(font)
        self.localsearchRadiobutton.setObjectName("localsearchRadiobutton")
        self.verticalLayout.addWidget(self.localsearchRadiobutton)
        self.onlinesearchRadiobutton = QtWidgets.QCheckBox(parent=self.selectionFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.onlinesearchRadiobutton.sizePolicy().hasHeightForWidth())
        self.onlinesearchRadiobutton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.onlinesearchRadiobutton.setFont(font)
        self.onlinesearchRadiobutton.setIconSize(QtCore.QSize(20, 20))
        self.onlinesearchRadiobutton.setChecked(False)
        self.onlinesearchRadiobutton.setObjectName("onlinesearchRadiobutton")
        self.verticalLayout.addWidget(self.onlinesearchRadiobutton)
        self.onlinesearchRadiobutton_2 = QtWidgets.QCheckBox(parent=self.selectionFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.onlinesearchRadiobutton_2.sizePolicy().hasHeightForWidth())
        self.onlinesearchRadiobutton_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.onlinesearchRadiobutton_2.setFont(font)
        self.onlinesearchRadiobutton_2.setIconSize(QtCore.QSize(20, 20))
        self.onlinesearchRadiobutton_2.setChecked(False)
        self.onlinesearchRadiobutton_2.setObjectName("onlinesearchRadiobutton_2")
        self.verticalLayout.addWidget(self.onlinesearchRadiobutton_2)
        self.verticalLayout_2.addWidget(self.selectionFrame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Title.setText(_translate("Dialog", "Validation Settings"))
        self.configButton.setText(_translate("Dialog", "..."))
        self.transferfileRadiobutton.setText(_translate("Dialog", "Force Type Validation"))
        self.localsearchRadiobutton.setText(_translate("Dialog", "Disable Area Validation"))
        self.onlinesearchRadiobutton.setText(_translate("Dialog", "Disable Constraing Validation"))
        self.onlinesearchRadiobutton_2.setText(_translate("Dialog", "Mark All Objects as Accessible"))
