# Form implementation generated from reading ui file 'c:\Users\mauri\Repos\GitHub\iligui\dialog_settings.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(302, 227)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\mauri\\Repos\\GitHub\\iligui\\icons/interlis.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("QRadioButton::indicator:checked, QCheckBox::indicator:checked {\n"
"    image: url(icons/check-circle-green.svg);\n"
"}\n"
"QRadioButton::indicator:unchecked, QCheckBox::indicator:unchecked {\n"
"    image: url(icons/circle.svg);\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Title = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.Title.setFont(font)
        self.Title.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.Title.setObjectName("Title")
        self.horizontalLayout.addWidget(self.Title)
        self.configButton = QtWidgets.QToolButton(parent=self.frame)
        self.configButton.setMinimumSize(QtCore.QSize(30, 30))
        self.configButton.setStyleSheet("QToolButton[objectName^=\"configButton\"]:hover {\n"
"    background-color : rgb(230,230,230);\n"
"    border-radius: 15px;\n"
"    border-style: outset;\n"
"}\n"
"\n"
"\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\mauri\\Repos\\GitHub\\iligui\\icons/tool.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.configButton.setIcon(icon1)
        self.configButton.setIconSize(QtCore.QSize(30, 30))
        self.configButton.setAutoRaise(True)
        self.configButton.setObjectName("configButton")
        self.horizontalLayout.addWidget(self.configButton)
        self.verticalLayout_2.addWidget(self.frame)
        self.selectionFrame = QtWidgets.QFrame(parent=Dialog)
        self.selectionFrame.setEnabled(True)
        self.selectionFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.selectionFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.selectionFrame.setObjectName("selectionFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.selectionFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.validationOption0 = QtWidgets.QCheckBox(parent=self.selectionFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.validationOption0.sizePolicy().hasHeightForWidth())
        self.validationOption0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.validationOption0.setFont(font)
        self.validationOption0.setStyleSheet("")
        self.validationOption0.setCheckable(True)
        self.validationOption0.setChecked(False)
        self.validationOption0.setObjectName("validationOption0")
        self.verticalLayout.addWidget(self.validationOption0)
        self.validationOption1 = QtWidgets.QCheckBox(parent=self.selectionFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.validationOption1.sizePolicy().hasHeightForWidth())
        self.validationOption1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.validationOption1.setFont(font)
        self.validationOption1.setObjectName("validationOption1")
        self.verticalLayout.addWidget(self.validationOption1)
        self.validationOption2 = QtWidgets.QCheckBox(parent=self.selectionFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.validationOption2.sizePolicy().hasHeightForWidth())
        self.validationOption2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.validationOption2.setFont(font)
        self.validationOption2.setIconSize(QtCore.QSize(20, 20))
        self.validationOption2.setChecked(False)
        self.validationOption2.setObjectName("validationOption2")
        self.verticalLayout.addWidget(self.validationOption2)
        self.validationOption3 = QtWidgets.QCheckBox(parent=self.selectionFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.validationOption3.sizePolicy().hasHeightForWidth())
        self.validationOption3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.validationOption3.setFont(font)
        self.validationOption3.setIconSize(QtCore.QSize(20, 20))
        self.validationOption3.setChecked(False)
        self.validationOption3.setObjectName("validationOption3")
        self.verticalLayout.addWidget(self.validationOption3)
        self.verticalLayout_2.addWidget(self.selectionFrame)
        self.okButton = QtWidgets.QPushButton(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.okButton.sizePolicy().hasHeightForWidth())
        self.okButton.setSizePolicy(sizePolicy)
        self.okButton.setMinimumSize(QtCore.QSize(170, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.okButton.setFont(font)
        self.okButton.setStyleSheet("QPushButton[objectName^=\"okButton\"]:hover {\n"
"    background-color : rgb(230,230,230);\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"}\n"
"\n"
"")
        self.okButton.setFlat(True)
        self.okButton.setObjectName("okButton")
        self.verticalLayout_2.addWidget(self.okButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Settings Selection"))
        self.Title.setText(_translate("Dialog", "Validation Settings"))
        self.configButton.setText(_translate("Dialog", "..."))
        self.validationOption0.setText(_translate("Dialog", "Force Type Validation"))
        self.validationOption1.setText(_translate("Dialog", "Disable Area Validation"))
        self.validationOption2.setText(_translate("Dialog", "Disable Constraing Validation"))
        self.validationOption3.setText(_translate("Dialog", "Mark All Objects as Accessible"))
        self.okButton.setText(_translate("Dialog", "OK"))
